---
- name: Deploy infra stack Apache, Nodejs runtime and App
  hosts: web
  tasks:
  - name: latest Apache version installed
    yum:
      name: httpd
      state: latest
  
  - name: latest python2-dnf version installed
    yum:
      name: python2-dnf
      state: latest
  
  - name: latest python3-dnf version installed
    yum:
      name: python3-dnf
      state: latest           

  - name: install apache proxy definition
    copy:
      src: nodeproxy.conf
      dest: /etc/httpd/conf.d/nodeproxy.conf
    notify: apache-reload

  - name: Allow SELinux Apache Proxy connect
    seboolean:
      name: httpd_can_network_connect
      state: yes
      persistent: yes

  - name: Allow SELinux Apache Proxy relay
    seboolean:
      name: httpd_can_network_relay
      state: yes
      persistent: yes

  - name: latest firewalld version installed
    yum:
      name: firewalld
      state: latest

  - name: firewalld enabled and running
    service:
      name: firewalld
      enabled: true
      state: started

  - name: firewalld permits http service
    firewalld:
      service: http
      permanent: true
      state: enabled
      immediate: yes

  - name: Apache enabled and running
    service:
      name: httpd
      enabled: true
      state: started

  - name: install nodejs
    dnf:
      name: '@nodejs/development'
      state: present

  - name: install nodejs systemd unit file
    copy:
      src: node.service
      dest: /etc/systemd/system/node.service
    notify: systemd-reload

  handlers:
  - name: systemd-reload
    systemd:
      daemon_reload: yes

  - name: apache-reload
    systemd:
      name: httpd
      state: reloaded
