---
- name: Apache server installed
  hosts: web

  tasks:
  - name: latest Apache version installed
    yum:
      name: httpd
      state: latest
  
  - name: Apache enabled and running
    service:
      name: httpd
      enabled: true
      state: started
